Admin profile validation
HITK-TECH-Community/Community-Website pull request #1047
Opened 2024-06-12 19:16 UTC by ayushpatel1248

## Issue that this pull request solves

- previously if we try ot update the admin profile username due to validation admin was not able to enter the numbers or _ in there validation 

- but now i have changed the validation and now admin can use number as well as _ in there username 

 Closes: #1042 

## Proposed changes

- in this i have changed the validation by changing the username schema where i have changed the regular expression for the username so that now admin can include numbers as well as the special _ type symbols in there username

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

https://github.com/HITK-TECH-Community/Community-Website/assets/127100604/421deec0-ae30-40af-a0d7-0a203c1089da

2024-06-15 16:27 UTC, Kajol-Kumari requested changes
@ayushpatel1248 there are so many unnecessary change in this file that its hard to follow, please clean it up and only keep the required changes

2024-06-15 16:27 UTC, Kajol-Kumari commented on frontend/src/pages/Q&A/Q&A.jsx
> +          setButtonPressed(false);
Why is this change again coming?

2024-06-15 17:35 UTC, ayushpatel1248 commented
@Kajol-Kumari  removed the unnecessary changes and kept only required changes , please check it out

2024-06-16 13:37 UTC, Kajol-Kumari approved these changes

2024-06-16 13:38 UTC, Kajol-Kumari commented
@ayushpatel1248  i don' see the second part of the issue in this pr - https://github.com/HITK-TECH-Community/Community-Website/issues/1042#issuecomment-2163461523

2024-06-20 11:36 UTC, merged