Bug Fixed: The respective image should appear in the Recent&Previous Broadcast Cards
HITK-TECH-Community/Community-Website pull request #1095
Opened 2024-07-30 19:17 UTC by shivamgaur99

The respective image should appear in the Recent&Previous Broadcast Cards

## Issue that this pull request solves

 Closes: #1090

![image](https://github.com/user-attachments/assets/f0ae9165-3863-47b1-bf05-35a6e6cd9a59)

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

2024-07-30 19:18 UTC, shivamgaur99 commented
@Kajol-Kumari please review in your free time

2024-07-31 17:17 UTC, Kajol-Kumari requested changes

2024-07-31 17:17 UTC, Kajol-Kumari commented on frontend/src/pages/Broadcast/Component/Carousel/Carousel.jsx
> +      // clipPath: "polygon(0 0, 100% 0, 100% 70%, 50% 100%, 0 70%)",
why this?

2024-07-31 17:17 UTC, Kajol-Kumari commented on frontend/src/pages/Broadcast/Component/Carousel/Carousel.jsx
> +      //backgroundSize: "cover", // Cover the entire area
remove all commented code and i would prefer the image to cover the whole space instead of fixed height

2024-07-31 17:17 UTC, Kajol-Kumari commented on frontend/src/pages/Broadcast/Component/Carousel/Carousel.jsx
> +      // clipPath: "polygon(0 0, 100% 0, 100% 70%, 50% 100%, 0 70%)",
remove, if not required

2024-07-31 17:17 UTC, Kajol-Kumari commented on frontend/src/pages/Broadcast/Component/Carousel/Carousel.jsx
> +      //backgroundSize: "cover", // Cover the entire area
remove if not required

2024-07-31 18:40 UTC, shivamgaur99 commented
@Kajol-Kumari i am closing this pr will make another one

2024-07-31 18:40 UTC, closed without merging