Improved Footer
HITK-TECH-Community/Community-Website pull request #127
Opened 2020-12-28 17:55 UTC by Swastik1710

## Issue that this pull request solves:  Improves the footer component.

 Closes: #125

## Proposed changes: Updated the icons, added Newsletter column and made the footer more attractive .

### Brief description of what is fixed or changed: Made the footer component more attractive.

## Types of changes : Representation improvements

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality) Newsletter added
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots
![Final](https://user-images.githubusercontent.com/71871571/103231738-9629b000-495e-11eb-9647-4dc17a972d82.png)

## Other information

2020-12-29 07:57 UTC, Kajol-Kumari requested changes
@Swastik1710 Can we please have something like this 
![Screenshot from 2020-12-29 13-25-05](https://user-images.githubusercontent.com/44888949/103268397-5fdd4680-49d9-11eb-8873-030718b7254a.png)

Just make the title `Sign Up for our Newsletter` to have same look as `Navigation` text in footer and the background color for bottom-most div is `#016795`

2020-12-29 08:25 UTC, Swastik1710 commented
Yeah sure. I'll get back to you after making the changes.

2020-12-29 13:44 UTC, Swastik1710 commented
Hey @Kajol-Kumari , I have made the required changes. Please have a look and let me know if any other changes are required.

2020-12-29 14:34 UTC, Kajol-Kumari requested changes
@Swastik1710 THans for incorporating the requested changes. Please do these minor changes and reduce a bit of space between the contents and that `pink line`. Then it will be good to go :)

2020-12-29 14:34 UTC, Kajol-Kumari commented on frontend/src/components/footer/footer.css
> +  border-top: 3px solid black;
please remove this line and add 
```
  font-size: 14px;
  font-weight: 600;
```

2020-12-29 14:34 UTC, Kajol-Kumari commented on frontend/src/components/footer/footer.js
> +          {/* <a
please remove these commented lines as we won't require this anymore

2020-12-29 14:34 UTC, Kajol-Kumari commented on frontend/src/components/footer/footer.js
> +      <div class="footer-dash">
replace all `class` with `className`

2020-12-29 15:16 UTC, Swastik1710 commented
Hey @Kajol-Kumari , kindly review the changes and let me know if any further changes required.

2020-12-30 08:04 UTC, Kajol-Kumari requested changes
@Swastik1710 Footer is looking great! But somehow the website is getting distorted for small s
![Screenshot from 2020-12-30 13-32-12](https://user-images.githubusercontent.com/44888949/103338256-cb8be600-4aa3-11eb-8f13-8df75960499a.png)
creens, please fix that and it will be good to go :)

2020-12-30 10:09 UTC, Swastik1710 commented
@Kajol-Kumari , I've fixed this issue for both mobile and tab view. Please let me know if any further changes are required.

2020-12-30 12:00 UTC, Kajol-Kumari commented
Hey @Swastik1710 please resolve the conflict so that I can merge this :)

2020-12-30 12:24 UTC, Swastik1710 commented
Done.

2020-12-30 12:31 UTC, Kajol-Kumari commented
> Done.

Seems like, something got messed up as i am getting blank space at smaller screen

![Screenshot from 2020-12-30 18-00-17](https://user-images.githubusercontent.com/44888949/103351352-fc324680-4ac8-11eb-9e07-cb3be7f86528.png)

2020-12-30 13:39 UTC, Swastik1710 commented
All done. Please have a look.

2020-12-30 14:26 UTC, Kajol-Kumari requested changes
@Swastik1710 Why am I seeing 4000+ lines of file change. Please remove the unnecessary chanegs

2020-12-30 15:12 UTC, Swastik1710 commented
After I resolved the conflicts , when I tried to do git push it showed an error telling me to do Git pull. And after doing git pull when I did git push these two errors showed up:- 
Module not found: Cannot resolve 'styled-component' 
Module not found: Cannot resolve 'semantic-ui-css' 

So I did
npm i semantic-ui-react semantic-ui-css
npm i styled-components

which solved the errors and this only caused 4k+ lines of changes.

So what do you want me to do now ?

2020-12-30 16:39 UTC, Kajol-Kumari commented
@Swastik1710 do this 
1. Copy the relevant codes somewhere as I can see you have made the PR using your `main` branch
2. Reset your head with upstream head 
```
git remote add upstream https://github.com/HITK-TECH-Community/Community-Website.git
git fetch upstream
git checkout main
git reset --hard upstream/main  
git push origin main --force
```
This will make your main branch even with the main repository.
After this, make a new branch (you can google it, if you don't know) and then put your code in there, push the change sand then make a new PR.

2020-12-30 17:09 UTC, closed without merging