implemented resource sharing page for DWoC
HITK-TECH-Community/Community-Website pull request #132
Opened 2020-12-29 14:42 UTC by vedikaag99

## Issue that this pull request solves

 Closes: # (issue number)

## Proposed changes

### Brief description of what is fixed or changed

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

2020-12-29 14:46 UTC, vedikaag99 commented
https://user-images.githubusercontent.com/67699840/103291871-b3b85180-4a12-11eb-96ac-5c6dfdcd6852.mov

2020-12-29 14:59 UTC, Kajol-Kumari requested changes
@vedikaag99 design looks great! Just make these minor changes and it will be good to go :)

2020-12-29 14:59 UTC, Kajol-Kumari commented on frontend/src/components/resource/resources.css
> +  .resource-input {
please leave one line space at the end of each class in css file

2020-12-29 14:59 UTC, Kajol-Kumari commented on frontend/src/components/resource/resources.css
> +  }
please leave one extra blank line at the end of the file

2020-12-29 14:59 UTC, Kajol-Kumari commented on frontend/src/components/resource/resources.css
> +    /* display: flex; */
please remove the commented line

2020-12-29 16:40 UTC, vedikaag99 commented on frontend/src/components/resource/resources.css
> +    /* display: flex; */
I have made the required changes.

2020-12-30 07:59 UTC, Kajol-Kumari approved these changes
LGTM :+1:

2020-12-30 08:00 UTC, merged