Login page
HITK-TECH-Community/Community-Website pull request #200
Opened 2021-01-06 12:14 UTC by vaishnavirshah

## Issue that this pull request solves

 Closes: #99 

## Proposed changes

I have added an image for login page, changed the position of the login section and made it similar to Contact us Page.

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

![](https://user-images.githubusercontent.com/61752840/103646844-59724000-4f80-11eb-8089-f2b76cd3fe13.png)

## Other information

Any other information that is important to this pull request

2021-01-06 13:53 UTC, vaishnavirshah commented
@Kajol-Kumari  is this fine?
![image](https://user-images.githubusercontent.com/61752840/103775754-84c65f00-5054-11eb-9192-5bf1e2467c7c.png)

2021-01-06 15:17 UTC, mohit355 commented on frontend/src/components/auth/loginPage-VaishnaviShah/login.css
> +  /* .login-card {
Remove unnecessary code

2021-01-06 15:35 UTC, vaishnavirshah commented on frontend/src/components/auth/loginPage-VaishnaviShah/login.css
> +  /* .login-card {
Done @mohit355

2021-01-06 16:17 UTC, mohit355 approved these changes

2021-01-06 16:57 UTC, salil-naik requested changes
@vaishnavirshah Good job with the login page. I have a few suggestions. 

Please use **[bootstrap grid](https://getbootstrap.com/docs/4.0/layout/grid/)** to place image and login form beside each other. Using *position*, *translate* and *margin* properties to place elements in line is a bad approach. That layout can easily be achieved with the help of a bootstrap grid.  

Let us know if you need any help.

2021-01-06 16:59 UTC, vaishnavirshah commented
> @vaishnavirshah Good job with the login page. I have a few suggestions.
> 
> Please use **[bootstrap grid](https://getbootstrap.com/docs/4.0/layout/grid/)** to place image and login form beside each other. Using _position_, _translate_ and _margin_ properties to place elements in line is a bad approach. That layout can easily be achieved with the help of a bootstrap grid.
> 
> Let us know if you need any help.

@salil-naik  I had tried using bootstrap initially but I was not able to import it into my login file, if you could help me with that - it will be great.

2021-01-06 17:12 UTC, salil-naik commented
> > @vaishnavirshah Good job with the login page. I have a few suggestions.
> > Please use **[bootstrap grid](https://getbootstrap.com/docs/4.0/layout/grid/)** to place image and login form beside each other. Using _position_, _translate_ and _margin_ properties to place elements in line is a bad approach. That layout can easily be achieved with the help of a bootstrap grid.
> > Let us know if you need any help.
> 
> @salil-naik I had tried using bootstrap initially but I was not able to import it into my login file, if you could help me with that - it will be great.

You need not import anything. Directly use the bootstrap classes and it should work.

2021-01-07 07:05 UTC, vaishnavirshah commented
@salil-naik I have used bootstrap grid in my code now. 
This is how it looks, is it fine?

![image](https://user-images.githubusercontent.com/61752840/103862116-7e7fc380-50e4-11eb-99ef-92203fadfb03.png)

And on smaller screen - 

![image](https://user-images.githubusercontent.com/61752840/103862227-b850ca00-50e4-11eb-8e1d-fe7a2caaa709.png)


Should I update the files?

2021-01-07 08:58 UTC, salil-naik commented
@vaishnavirshah It looks better 👌 But you need to push your changes in order for me to check your code.

2021-01-07 10:30 UTC, vaishnavirshah commented
@salil-naik I am not able to push my files into GitHub, could you help me with that?

![image](https://user-images.githubusercontent.com/61752840/103882127-5e123200-5101-11eb-87ef-64f7e6ce9631.png)

2021-01-08 13:14 UTC, Kajol-Kumari approved these changes
@vaishnavirshah Thanks for incorporating the suggested changes
LGTM :+1:

2021-01-08 13:14 UTC, merged