fix for #164
HITK-TECH-Community/Community-Website pull request #211
Opened 2021-01-07 06:31 UTC by atharva-upadhye-01

## Issue that this pull request solves
[Frontend] Make Get Involved page

 Closes: #164

## Proposed changes
Added get involved page

### Brief description of what is fixed or changed
Added route `/get-involved` and made changes to footer accordingly
Created getInvolved page in its respective folder structure and called that component in footer

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots
![image](https://user-images.githubusercontent.com/70993547/103857737-12e62800-50dd-11eb-9233-08d4481ee6fd.png)

2021-01-07 06:40 UTC, Kajol-Kumari requested changes
Hey @atharva-upadhye-01 please change the card color to `#016795` this also the font-family of the heading should be same as other page like home page

2021-01-07 12:35 UTC, atharva-upadhye-01 commented
@Kajol-Kumari  Can you please add DWOC ?
I have enrolled in it.

2021-01-07 14:03 UTC, Kajol-Kumari requested changes
Hey @atharva-upadhye-01 thanks for incorporating the suggested changes please make the minor change sand fix the heading fir small screen and it will be good to go :)
![Screenshot from 2021-01-07 19-31-19](https://user-images.githubusercontent.com/44888949/103901506-3df16b80-511f-11eb-8d04-49dc83168ffd.png)

2021-01-07 14:03 UTC, Kajol-Kumari commented on frontend/src/components/involvement/get_involved.js
> +// import icon from
please remove this line

2021-01-07 14:03 UTC, Kajol-Kumari commented on frontend/src/components/involvement/get_involved.css
> +}
leave one line space at the end of file

2021-01-07 14:15 UTC, Surajbokde requested changes
@atharva-upadhye-01 
change card background color to **#121f3a;**
and on hovermake it   gradient color
**background: rgb(255, 0, 90);
  background: linear-gradient(
    45deg,
    rgba(255, 0, 90, 1) 0%,
    rgba(10, 24, 61, 1) 90%
  );**

2021-01-07 14:15 UTC, Surajbokde commented on frontend/src/components/involvement/get_involved.css
> +    font-family: Lato,'Helvetica Neue',Arial,Helvetica,sans-serif;
font-family: "Futura LT Book", sans-serif;

make this change

2021-01-07 14:26 UTC, Kajol-Kumari commented
> @atharva-upadhye-01
> change card background color to **#121f3a;**
> and on hovermake it gradient color
> **background: rgb(255, 0, 90); background: linear-gradient( 45deg, rgba(255, 0, 90, 1) 0%, rgba(10, 24, 61, 1) 90% );**

Hey @Surajbokde  believe the color combination is looking preety good so let's stick with the one that is already implemented in this PR :)

\cc: @atharva-upadhye-01

2021-01-07 15:25 UTC, chait04 commented on frontend/src/components/involvement/get_involved.js
> +        {arrayCards.map(element => {
provide key to the div.. put ( i ) as a argument in map function and just pass i as key to div

2021-01-08 06:43 UTC, mohit355 requested changes

2021-01-08 06:43 UTC, mohit355 commented on frontend/src/components/involvement/get_involved.js
> +            <div className="card-item">
Pass a key parameter to this div.
Use the 2nd parameter of the map function as a key for the first div that mounted all other tags inside the map function.
ex: -  key={ index}    'index;   is the 2nd parameter.

2021-01-08 12:37 UTC, atharva-upadhye-01 commented
Let me know suggestions if any :)

2021-01-08 13:02 UTC, Kajol-Kumari approved these changes
Hey @atharva-upadhye-01 thanks for incorporating the suggested changes. It looks good to me :)

2021-01-08 13:03 UTC, merged