Our motives
HITK-TECH-Community/Community-Website pull request #230
Opened 2021-01-08 17:52 UTC by urvashi-code1255

## Issue that this pull request solves

 Closes: #213 

## Proposed changes
Add the content provided for motive page.

### Brief description of what is fixed or changed
Added the content and the relevent icons in the motive section of home page.

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface
![Capture](https://user-images.githubusercontent.com/63122133/104047824-205fe880-5197-11eb-9332-892fcf243212.PNG)

## Other information

Any other information that is important to this pull request

2021-01-09 08:32 UTC, tejan-singh requested changes

2021-01-09 08:32 UTC, tejan-singh commented on frontend/src/components/home/motive/motive.js
> +                <h4 className="features-title"><a href="/#">Get Inspired</a></h4>
You can remove this dummy data card. We are keeping only the updated cards

2021-01-09 08:32 UTC, tejan-singh commented on frontend/src/components/home/motive/motive.js
> +                  <a href="/#">Networking Session</a>
You can remove this dummy data card. We are keeping only the updated cards

2021-01-09 08:32 UTC, tejan-singh commented on frontend/src/components/home/motive/motive.js
> +                <h4 className="features-title"><a href="/#">Meet New Faces</a></h4>
You can remove this dummy data card. We are keeping only the updated cards

2021-01-09 09:57 UTC, mohit355 commented on frontend/src/components/auth/login/login.css
> +/* .login-btn {
Remove the  extra code

2021-01-09 09:57 UTC, mohit355 commented on frontend/src/components/contact/contact_us.css
> +/* .contact-input input:focus,
Remove these extra commented code

2021-01-09 10:37 UTC, Surajbokde approved these changes

2021-01-09 10:37 UTC, Surajbokde commented on frontend/src/components/auth/login/login.css
> +  /* border-color: #1863ff !important ; */
remove this comment

2021-01-09 11:18 UTC, urvashi-code1255 commented
@tejan-singh @mohit355 @Surajbokde I did all the changes. Please check..

2021-01-09 13:24 UTC, Surajbokde approved these changes

2021-01-09 17:08 UTC, tejan-singh approved these changes

2021-01-10 10:43 UTC, mohit355 approved these changes

2021-01-10 10:44 UTC, merged

2021-01-11 10:41 UTC, urvashi-code1255 commented
@Kajol-Kumari @jackfrost13 I am Dwoc And Swoc participant .