Resources UI
HITK-TECH-Community/Community-Website pull request #237
Opened 2021-01-09 11:11 UTC by carbseater

## Issue that this pull request solves

 Closes: #224  (issue number)

## Proposed changes

### Brief description of what is fixed or changed
       Resources UI improvement
## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [x] Other (please describe): 
     Mainly the frontend part
## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Here is the mobile view, the paddings are adjusted so that trust level checkboxes are in a line
![mobile-view](https://user-images.githubusercontent.com/59422042/104089927-e6770b00-5298-11eb-8484-2fd7f091c029.JPG)
These are the dektop view(added icons, hover effects, input background, box-shadow)
![1](https://user-images.githubusercontent.com/59422042/104089948-19210380-5299-11eb-89ba-633e69537b3d.JPG)
![2](https://user-images.githubusercontent.com/59422042/104089950-1f16e480-5299-11eb-99bd-fbfeb5f8fbec.JPG)

## Other information

I messed up last time making this PR so i have created this new separate PR with the improvements suggested by @vrushti-mody (about mobile-view button text size and paddings) @Kajol-Kumari

2021-01-09 11:15 UTC, carbseater commented
> ## Issue that this pull request solves
> Closes: #224 (issue number)
> 
> ## Proposed changes
> ### Brief description of what is fixed or changed
> ```
>    Resources UI improvement
> ```
> 
> ## Types of changes
> _Put an `x` in the boxes that apply_
> 
> * [ ]  Bugfix (non-breaking change which fixes an issue)
> * [ ]  New feature (non-breaking change which adds functionality)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
> * [ ]  Documentation update (Documentation content changed)
> * [x]  Other (please describe):
>   Mainly the frontend part
> 
> ## Checklist
> _Put an `x` in the boxes that apply_
> 
> * [x]  My code follows the style guidelines of this project
> * [x]  I have performed a self-review of my own code
> * [x]  I have commented my code, particularly in hard-to-understand areas
> * [x]  I have made corresponding changes to the documentation
> * [x]  My changes generate no new warnings
> * [x]  My changes does not break the current system and it passes all the current test cases.
> 
> ## Screenshots
> Here is the mobile view, the paddings are adjusted so that trust level checkboxes are in a line
> ![mobile-view](https://user-images.githubusercontent.com/59422042/104089927-e6770b00-5298-11eb-8484-2fd7f091c029.JPG)
> These are the dektop view(added icons, hover effects, input background, box-shadow)
> ![1](https://user-images.githubusercontent.com/59422042/104089948-19210380-5299-11eb-89ba-633e69537b3d.JPG)
> ![2](https://user-images.githubusercontent.com/59422042/104089950-1f16e480-5299-11eb-99bd-fbfeb5f8fbec.JPG)
> 
> ## Other information
> I messed up last time making this PR so i have created this new separate PR with the improvements suggested by @vrushti-mody (about mobile-view button text size and paddings) @Kajol-Kumari

Please review @vrushti-mody

2021-01-09 16:58 UTC, Kajol-Kumari requested changes
Hey @carbseater I tested this PR and would like to suggest few changes

1. Make the onlick box-shadow same as `contact-us` page. You can take reference from [here](https://github.com/HITK-TECH-Community/Community-Website/pull/228/files) 
2. Put some standard hover effect to icons(take reference from `contact-us` page) 
Rest looks good to go :)

2021-01-10 05:58 UTC, carbseater commented
> Hey @carbseater I tested this PR and would like to suggest few changes
> 
> 1. Make the onlick box-shadow same as `contact-us` page. You can take reference from [here](https://github.com/HITK-TECH-Community/Community-Website/pull/228/files)
> 2. Put some standard hover effect to icons(take reference from `contact-us` page)
>    Rest looks good to go :)

1. I have made the box-shadow same as the contact-us page, have a look
![Capture1](https://user-images.githubusercontent.com/59422042/104115581-d150b980-5336-11eb-8656-1541d2491300.JPG)

2.  I made some standard hover effect (referenced from contact page)
![Capture](https://user-images.githubusercontent.com/59422042/104115605-f2190f00-5336-11eb-86d5-1f1b45096867.JPG)

Give reviews @Kajol-Kumari

2021-01-10 08:22 UTC, Kajol-Kumari approved these changes
Thanks for incorporating suggested changes @carbseater 
LGTM 👍

2021-01-10 08:23 UTC, Kajol-Kumari commented
@carbseater please mention in the PR description if you have made this pr under swoc or dwoc

2021-01-10 08:39 UTC, carbseater commented
> @carbseater please mention in the PR description if you have made this pr under swoc or dwoc

I am a DWOC participant. Thanks @Kajol-Kumari

2021-01-10 08:57 UTC, merged