[Backend] API Testing for admin login #81
HITK-TECH-Community/Community-Website pull request #251
Opened 2021-01-11 22:42 UTC by kenkirito

## Issue that this pull request solves

 Closes: # (issue number)

## Proposed changes

### Brief description of what is fixed or changed

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

2021-01-11 22:42 UTC, kenkirito commented
@jackfrost13 please check

2021-01-15 14:33 UTC, jackfrost13 commented
Will complete all the pending PR's over the weekend. inconvenience regretted!

2021-01-17 10:09 UTC, jackfrost13 requested changes
Please add more sample request to cover all cases for login like failed password, missing body parameters etc

2021-01-17 10:09 UTC, jackfrost13 commented on postman/Login form
> +									"    pm.expect(jsonData).to.be.a('object');\r",
not needed

2021-01-17 10:09 UTC, jackfrost13 commented on postman/Login form
> +									"pm.test(\"400 invalid request\", function () {\r",
How can you have a contradicting test? One for 200 another for bad request

2021-01-17 10:09 UTC, jackfrost13 commented on postman/Login form
> +						"auth": {
Why do you need auth for login?

2021-01-17 10:25 UTC, jackfrost13 commented
you may refer to [this](https://github.com/HITK-TECH-Community/Community-Website/pull/244#issuecomment-758199289) for a getting some ideas

2021-01-17 14:32 UTC, jackfrost13 commented
I cannot see any further commits!

2021-01-17 14:35 UTC, kenkirito commented
i have made into main branch

2021-01-17 14:50 UTC, jackfrost13 commented
> i have made into main branch. #81

You need to add commits to a PR

2021-01-17 21:15 UTC, closed without merging