404 page enhanced for DWoC
HITK-TECH-Community/Community-Website pull request #293
Opened 2021-01-23 06:36 UTC by vedikaag99

## Issue that this pull request solves

 Closes: #287 (issue number)

## Proposed changes

### Brief description of what is fixed or changed

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request
no

@Kajol-Kumari Please check this PR as I was having trouble with the previous one.

2021-01-23 13:08 UTC, Kajol-Kumari requested changes
Hey @vedikaag99 please format the css file and make the page somewhat like this :point_down: 
![Screenshot from 2021-01-23 18-34-05](https://user-images.githubusercontent.com/44888949/105579048-0e429480-5daa-11eb-980e-0593bf2c24ea.png)

2021-01-23 13:08 UTC, Kajol-Kumari commented on frontend/src/components/404/not_found.css
> +  font-size: 21px;
let's make it 16px

2021-01-23 13:08 UTC, Kajol-Kumari commented on frontend/src/components/404/not_found.css
> +  padding:16px;
let's make it `padding:8px 16px;`

2021-01-23 13:15 UTC, Kajol-Kumari commented
Also don't forget the hover effect on the `go Home!` button :)

2021-01-23 16:01 UTC, vedikaag99 commented
@Kajol-Kumari I have made the required changes. Please check.

2021-01-24 06:10 UTC, Kajol-Kumari approved these changes
LGTM :+1:

2021-01-24 06:11 UTC, merged