Backend setup
HITK-TECH-Community/Community-Website pull request #323
Opened 2021-01-31 16:34 UTC by tanay13

## Issue that this pull request solves

 Closes: # 321

## Proposed changes

### Brief description of what is fixed or changed

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

2021-01-31 16:36 UTC, tanay13 commented
@jackfrost13 please review this

2021-02-07 17:37 UTC, jackfrost13 requested changes

2021-02-07 17:37 UTC, jackfrost13 commented on backend/docs/admin.md
> +- <code> <b> /admin </b> </code>
you can keep it like `/admin` [GET] such that you can avoid method : GET

2021-02-07 17:37 UTC, jackfrost13 commented on backend/docs/admin.md
> +        | Parameter   |
Please add the full table, follow my comments from auth review

2021-02-07 19:23 UTC, tanay13 commented
@jackfrost13  Please review i made the changes

2021-02-08 05:42 UTC, Kajol-Kumari approved these changes
@tanay13 Please do these minor changes and rest LGTM :+1:

2021-02-08 05:42 UTC, Kajol-Kumari commented on backend/docs/admin.md
> +    - For creating admin account
Please replace this line with `Create a new admin account`

2021-02-08 05:42 UTC, Kajol-Kumari commented on backend/docs/admin.md
> +    - To change the existing user's password
Please change this line to `Change the existing admin's Password`

2021-02-08 07:10 UTC, tanay13 commented
@Kajol-Kumari Please review i made the changes

2021-02-08 08:47 UTC, jackfrost13 requested changes

2021-02-08 08:47 UTC, jackfrost13 commented on backend/docs/admin.md
> +- [<b>GET</b> ] :<code> <b> /admin </b> </code>
Refer https://github.com/HITK-TECH-Community/Community-Website/pull/357#discussion_r571865409

2021-02-08 13:32 UTC, tanay13 commented
@jackfrost13 Please review , i made the changes

2021-02-10 06:48 UTC, jackfrost13 approved these changes

2021-02-10 06:48 UTC, merged

2021-02-10 08:16 UTC, Kajol-Kumari commented
Hey @tanay13 Just to confirm. You made this PR under SWOC?

2021-02-10 08:32 UTC, tanay13 commented
@Kajol-Kumari Yes both my PRs are under SWOC