Url shortener
HITK-TECH-Community/Community-Website pull request #324
Opened 2021-01-31 21:15 UTC by nehaparmar99

## Issue that this pull request solves
 Link shortener service
 Closes: #153 

## Proposed changes

### Brief description of what is fixed or changed
Added a link shortener service which accepts a query parameter link and shortens it to a code of length 5. One using that link is redirected to the original link if valid, else an error is thrown.

## Types of changes
I've added the API testing file in the url folder itself named API Tests.postman_collection.json
_Put an `x` in the boxes that apply_

- [x] New feature (non-breaking change which adds functionality)
## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

2021-02-02 19:56 UTC, jackfrost13 commented
will try to have a look tomorrow
detailed review will be done mostly by Saturday

2021-02-07 14:40 UTC, jackfrost13 commented
Working on it

2021-02-07 15:54 UTC, jackfrost13 requested changes
Please check my comments
Apologies for delayed response

2021-02-07 15:54 UTC, jackfrost13 commented on backend/index.js
> +app.use(express.json({ extended: false }));
Why do you need this?

2021-02-07 15:54 UTC, jackfrost13 commented on backend/app/routes/url/redirecturl.js
> +  try {
We prefer using await-to-js. Please refactor

2021-02-07 15:54 UTC, jackfrost13 commented on backend/app/routes/url/redirecturl.js
> +      return res.status(404).json('No url found');
Please follow Error handling as we have implemented it in other routes

2021-02-07 15:54 UTC, jackfrost13 commented on backend/app/routes/url/redirecturl.js
> +      return res.status(200).json({ url: url.longUrl });
You should redirect to the long url

2021-02-07 15:54 UTC, jackfrost13 commented on backend/app/routes/url/redirecturl.js
> +    console.log(url);
commits should be free of console logs

2021-02-07 15:54 UTC, jackfrost13 commented on backend/app/routes/url/redirecturl.js
> +    res.status(500).json('server error');
please follow our coding practices for error handling

2021-02-07 15:54 UTC, jackfrost13 commented on backend/app/routes/url/shorturl.js
> +    res.status(401).json('Invalid long url');
please check our error handling and refactor

2021-02-07 15:54 UTC, jackfrost13 commented on backend/app/routes/url/shorturl.js
> +      console.log(err);
refactor error handling

2021-02-07 15:54 UTC, jackfrost13 commented on backend/app/routes/url/shorturl.js
> +  if (!validurl.isUri(baseUrl)) {
How is this related to the user?

2021-02-07 15:54 UTC, jackfrost13 commented on backend/app/routes/url/shorturl.js
> +  if (validurl.isUri(longUrl)) {
you should check this using validation schema
Please refer to other routes for ref

2021-02-07 15:54 UTC, jackfrost13 commented on backend/app/routes/url/shorturl.js
> +    try {
use await-to-js

2021-02-07 15:54 UTC, jackfrost13 commented on backend/app/routes/url/shorturl.js
> +  const urlCode = shortid.generate();
try using `nano id` instead of shortid, its faster and more reliable and you need not use substring later

2021-02-12 15:19 UTC, jackfrost13 commented
@nehaparmar99 Are you still working on this? Please update your status

2021-02-13 11:56 UTC, nehaparmar99 commented
> @nehaparmar99 Are you still working on this? Please update your status

Yes I am, I'll do it by tomorrow latest

2021-02-13 19:50 UTC, nehaparmar99 commented
@jackfrost13 I've made the changes.Please check it out.
Changes made:
1.Refactored error handling.
2.Nanoid used.
3.The shortUrl obtained now redirects to the Original long url

2021-02-20 07:37 UTC, nehaparmar99 commented
@jackfrost13 please review it

2021-02-20 08:31 UTC, jackfrost13 commented
Extremely sorry, slipped out of my review list.
Please make a habbit to request for re-review else we don't get notification

2021-02-20 14:12 UTC, jackfrost13 commented
@nehaparmar99 Hi, can you join for 15 mins meet? I can request for changes but since you have been blocked on this for a couple of days I have made changes and was thinking to help you on it

2021-02-20 18:28 UTC, jackfrost13 approved these changes

2021-02-20 18:29 UTC, merged

2021-02-20 18:31 UTC, jackfrost13 commented
Closes #153 
@nehaparmar99 Let me know if want a sync up on brief understanding as to why my changes are helpful, I will be available only on weekends

2021-02-25 19:35 UTC, jackfrost13 commented
Hi @nehaparmar99, we didn't hear back from you, please let me know if you had gone through my changes. The whole point of running this cohort sprint is to spread awareness and exchange knowledge and if you are not benefitting out of it then it defeats the whole purpose. We try our best to rely on high standard.

2021-02-27 06:09 UTC, nehaparmar99 commented
> Hi @nehaparmar99, we didn't hear back from you, please let me know if you had gone through my changes. The whole point of running this cohort sprint is to spread awareness and exchange knowledge and if you are not benefitting out of it then it defeats the whole purpose. We try our best to rely on high standard.

Hey I'm so sorry for not getting back.I had gone through the changes, and understood the point of them.I have been extremely busy with my college schedule, so couldn't find much time.I am so sorry for the delayed response.