modified newsletter
HITK-TECH-Community/Community-Website pull request #361
Opened 2021-02-06 11:50 UTC by AbhipsaGuru1012

## Issue that this pull request solves

 Closes: #338 (DWoC)

## Proposed changes
Fix Error message for Newsletter signup

### Brief description of what is fixed or changed
 Changed the error message for the Sign Up for our Newsletter input box.

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface
![newsletter](https://user-images.githubusercontent.com/58511560/107117310-90998100-689f-11eb-934b-f312de2a6feb.PNG)

## Other information

Any other information that is important to this pull request

2021-02-06 14:22 UTC, tejan-singh requested changes

2021-02-06 14:22 UTC, tejan-singh commented on frontend/src/components/footer/footer.css
> +}
please add margin-bottom: 25px

2021-02-06 15:07 UTC, tejan-singh requested changes
Please make changes for responsive design also.
You can make the message appear in center below the input box

![Capture1](https://user-images.githubusercontent.com/50990883/107121944-1e369a00-68bb-11eb-8751-991931a878da.PNG)

2021-02-07 16:30 UTC, AbhipsaGuru1012 commented
> Please make changes for responsive design also.
> You can make the message appear in center below the input box
> 
> ![Capture1](https://user-images.githubusercontent.com/50990883/107121944-1e369a00-68bb-11eb-8751-991931a878da.PNG)

@tejan-singh I am having some problem solving this issue. I will try to solve it and make the changes soon.

2021-02-08 05:55 UTC, AbhipsaGuru1012 commented
![newsletter-new](https://user-images.githubusercontent.com/58511560/107181192-51367600-6a00-11eb-87ad-86f116780128.PNG)

@tejan-singh @tripathyprateek I have made the changes. Please review.

2021-02-08 12:02 UTC, Kajol-Kumari approved these changes

2021-02-08 12:04 UTC, merged