Converted css files to css modules - section 4
HITK-TECH-Community/Community-Website pull request #364
Opened 2021-02-06 17:06 UTC by sakshikhachane

### SWOC and DWOC participant

## Issue that this pull request solves

 Closes: #349

## Proposed changes
Converted CSS to CSS modules section 4 -

- [x] FAQ.css
- [x] footer.css
- [x] motive.css
- [x] overview.css
- [x] home.css

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

2021-02-07 07:58 UTC, Kajol-Kumari requested changes
Hey @sakshikhachane as we don't have any file named as `motive.css`. Please make the requite changes in [here](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/home/carousel/carousel.js#L6) and related places along with [here](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/broadcast/Carousel/Carousel.js#L6) and required places in this file.

2021-02-07 10:13 UTC, sakshikhachane commented
@Kajol-Kumari Do I have to make changes in the classes of mentioned files as required for `motive.module.css` or make a new `motive.css` file?

2021-02-07 16:51 UTC, sakshikhachane commented
@Kajol-Kumari I have updated the files and done the changes requested. Please have a look.

2021-02-08 06:11 UTC, Kajol-Kumari requested changes
@sakshikhachane Thanks for incorporating the suggested changes. Just a minor change is required. Rest looks good to go :)

2021-02-08 06:11 UTC, Kajol-Kumari commented on frontend/src/components/home/carousel/carousel.js
>            <h1 style={{ color: "#121f3a" }}>Curious to know More about Us?</h1>
This is getting distorted for small screen. Can you please check and fix it

2021-02-08 06:31 UTC, sakshikhachane commented
@sakshikhachane I have done the changes. Please have a look.

2021-02-08 12:07 UTC, Kajol-Kumari commented
@sakshikhachane please resolve the conflicts.

2021-02-08 13:26 UTC, sakshikhachane commented
@Kajol-Kumari I have resolved the conflicts and updated the code.

2021-02-09 07:12 UTC, Kajol-Kumari approved these changes

2021-02-09 07:12 UTC, merged