Refactored Broadcasts
HITK-TECH-Community/Community-Website pull request #382
Opened 2021-02-13 07:26 UTC by nehaparmar99

## Issue that this pull request solves

 Closes: #372 

### Brief description of what is fixed or changed
 Made a test_data directory under frontend/src folder. Make a file named broadcasttext.js and added the broadcast data there.This json is rendered on the broadcast and all_broadcast page and also in the carousel

_Put an `x` in the boxes that apply_

- [x] New feature (non-breaking change which adds functionality)

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

2021-02-13 07:29 UTC, nehaparmar99 commented
@Kajol-Kumari review

2021-02-13 20:39 UTC, tejan-singh approved these changes
LGTM 👍🏻

2021-02-14 08:25 UTC, salil-naik requested changes
Hi @nehaparmar99 . Good work so far. 

Please do the following changes. 
- [ ] Use descriptive variable names

- [ ] use JSON file to store the data.

2021-02-14 08:25 UTC, salil-naik commented on frontend/src/components/broadcast/Carousel/Carousel.js
> +  let s1t = dataa[0].title;
Variable names should be self-descriptive as much as possible. Writing variables like s1t, s1d, etc is a bad practice.

2021-02-14 12:44 UTC, nehaparmar99 commented
@salil-naik made both the changes. please check

2021-02-14 15:12 UTC, Kajol-Kumari approved these changes
LGTM :+1:

2021-02-14 15:13 UTC, merged