Enhancement in Add Broadcast Page of Admin
HITK-TECH-Community/Community-Website pull request #420
Opened 2021-02-20 17:52 UTC by sakshikhachane

## Issue that this pull request solves

 Closes: #371 

## Proposed changes

- [x] Make the Page responsive
- [x]  Put everything on a card and add a submit button at the end of the card
- [x] Make sure to keep the navigation panel of the admin stick to left and render the edit toolbar on the right panel only

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface
![Screenshot (197)](https://user-images.githubusercontent.com/53635792/108604198-692fd180-73d2-11eb-8c68-260f5026d710.png)
![Screenshot (198)](https://user-images.githubusercontent.com/53635792/108604201-6e8d1c00-73d2-11eb-8a65-9c60f86cabbc.png)

2021-02-21 03:35 UTC, sakshikhachane commented
@tejan-singh I had discussed this point - `On hover, the placeholder should appear with appropriate size.` with Kajol and she said to leave this point and make PR for the rest of the points. 
Please review the PR.

2021-02-21 09:01 UTC, tejan-singh requested changes

2021-02-21 09:23 UTC, tejan-singh requested changes

2021-02-21 09:23 UTC, tejan-singh commented on frontend/src/components/admin/add_broadcasts/add_broadcasts.js
> +                    <Button2
- Please add `margin-top: 20px` on submit button

2021-02-21 09:26 UTC, tejan-singh requested changes
- Please remove all hover effects.

2021-02-21 10:32 UTC, Kajol-Kumari requested changes
@sakshikhachane apart from what @tejan-singh suggested , just one more enhancement, Please put this folder `add_broadcasts` under `admin/broadcast` folder.

2021-02-21 15:45 UTC, sakshikhachane commented
@tejan-singh I have done all the changes required. Please review the PR now.

2021-02-22 05:27 UTC, Kajol-Kumari approved these changes
LGTM :+1:

2021-02-22 05:28 UTC, merged