Sass for util components and terms page
HITK-TECH-Community/Community-Website pull request #426
Opened 2021-02-21 18:27 UTC by ashuvssut

## Issue that this pull request solves

 Closes #419 

------------------
_--I have participated in DWoC SWoC and MWoC_

2021-02-21 18:31 UTC, ashuvssut commented on frontend/src/components/Button/Button.jsx
> +      className={`${style["main-btn"]} ${style["main-btn-2"]} ${style["main-btn-3"]}`}
before: `className="main-btn main-btn-2 main-btn-3"`

after: `className={`${style["main-btn"]} ${style["main-btn-2"]} ${style["main-btn-3"]}`}`

in this line, if you can suggest a better clean way to write multiple css classes to an element, then I ll be glad to implement that.

2021-02-22 11:35 UTC, salil-naik approved these changes
Amazing job @ashuvssut 👌

2021-02-22 11:39 UTC, salil-naik commented
@Kajol-Kumari this PR follows the new folder structure. There was no `util` folder in the proposal. And hence we have conflicts. Should we retain the util folder? Or remove it and put `button` and `scroll-to-top` components in the `components` folder directly?

2021-02-22 12:11 UTC, ashuvssut commented
buttons, scroll-to-top are all reusable components that are used by all pages. so I thought keeping it in components folder is the right choice. so i deleted the utils folder😅😅

2021-02-22 12:14 UTC, AnjaliPatle requested changes
Hey @ashuvssut, great job! Just some small changes:
Instead of creating new folders for Button, Dropdown and ScrollToTop in `src/components` directly, please retain the util folder and add it under `src/components` with all other folders inside it.

2021-02-22 12:21 UTC, ashuvssut commented
new one must be like:-
`components/`--|
                          |--`util/`--|
                          |              |--`button/`
                          |              |--`scrollToTop/`
                          |              |--`dropdown/`


instead of current one which is like:-
`components/`--|
                          |
                          |--`button/`
                          |--`scrollToTop/`
                          |--`dropdown/`

Am I right? Is this the requirement?

2021-02-22 16:04 UTC, AnjaliPatle commented
Yes @ashuvssut , you are right.

2021-02-23 03:42 UTC, salil-naik commented
@ashuvssut you requested for review but nothing has been changed since I last reviewed. 😅  Maybe you forgot to push your changes?

2021-02-23 05:42 UTC, ashuvssut commented
@salil-naik, sorry for that😅😅

2021-02-23 05:54 UTC, Kajol-Kumari commented
@ashuvssut please resolve the conflict here

2021-02-23 06:58 UTC, ashuvssut commented
@Kajol-Kumari I resolved the 2nd merge conflict. Please review

2021-02-23 07:13 UTC, Kajol-Kumari approved these changes
Thanks for incorporating the suggested changes @ashuvssut 
LGTM :)

2021-02-23 07:15 UTC, merged