create pr template
HITK-TECH-Community/Community-Website pull request #44
Opened 2020-12-15 14:05 UTC by kenkirito

Add PR creation template #43

2020-12-15 14:24 UTC, Kajol-Kumari requested changes
Hey @kenkirito can we please have something similar to [this](https://github.com/Canvasbird/canvasboard/blob/master/.github/PULL_REQUEST_TEMPLATE.md) ?

2020-12-15 15:05 UTC, kenkirito reviewed
create pr template #43

2020-12-16 18:30 UTC, Kajol-Kumari approved these changes

2020-12-16 18:31 UTC, merged

2020-12-16 18:31 UTC, Kajol-Kumari commented
@all-contributors please add @kenkirito  for documentation