team section OK🌼
HITK-TECH-Community/Community-Website pull request #474
Opened 2021-03-01 11:33 UTC by ashuvssut

adds to #308 

NOTE:- this PR only gives about Us page's Team section the dynamic rendering

Some little UI changes are also there

Dark `box-shadow` is now lighter

---------------
_--I have participated in SWoC_

2021-03-01 14:48 UTC, Kajol-Kumari requested changes
@ashuvssut please do the following

1. Remove `Meet the Crew` section
2. Add dash line( same as on the broadcasts page ) below `Founders and Co-Founders` and `Core Members`
Also prove a bit of padding between them so that it will look more cleaner. Btw the card is looking better :)

2021-03-02 09:42 UTC, Kajol-Kumari approved these changes

2021-03-02 09:43 UTC, merged

2021-03-02 09:44 UTC, Kajol-Kumari commented
Thanks @ashuvssut  for taking the accountability to solve this Issue. But as this PR has been opened on 1st march and swoc officially ended on 28th only so I won't be able to give you the score for this.

2021-03-02 09:49 UTC, ashuvssut commented
No problem at all di!😊