About us
HITK-TECH-Community/Community-Website pull request #509
Opened 2021-03-11 19:20 UTC by Shubham-Kumar-2000

## Issue that this pull request solves

 Closes: #482 

## Proposed changes

About Us page should have two cards similar to faqs

Manage Teams
Add Team Member
Manage Teams will take us to a new page having cards with dummy data as of now.

Add Team Member card will take us to a page containing form with following fields along with a submit button -

Full Name
picture Upload
Short Description
linkedIn URL
Github URL
Twitter URL
Teams(Open Source, Broadcast, Design, Social, Resource Sharing) =>This will be a multiple select box with the options given
Please make sure to render the page on the right side keeping the left side navigation panel same for these pages.

### Brief description of what is fixed or changed

All Above mentioned changes have been done

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

![image](https://user-images.githubusercontent.com/41825906/110842213-d09fb980-82cc-11eb-898e-b0e59ac37967.png)
![image](https://user-images.githubusercontent.com/41825906/110842242-d9908b00-82cc-11eb-8aea-05ba9ac7c6b5.png)
![image](https://user-images.githubusercontent.com/41825906/110842267-e2815c80-82cc-11eb-9dd1-3f78be5298c5.png)
![image](https://user-images.githubusercontent.com/41825906/110842286-e90fd400-82cc-11eb-8ea0-a5da579dc620.png)

## Other information

NA

2021-03-12 08:19 UTC, Kajol-Kumari requested changes
Hey @Shubham-Kumar-2000 This looks super nice and clean Btw the issue was only for `add_team` but as you have created `manage teams` as well so I am changing the level of the issue :)

Please make the requested changes so that we can merge this.

2021-03-12 08:19 UTC, Kajol-Kumari commented on frontend/src/pages/Admin/Components/About/About.jsx
> +    {
Hey @Shubham-Kumar-2000 Please make these cards look like :arrow_down: 
![Screenshot from 2021-03-12 13-43-26](https://user-images.githubusercontent.com/44888949/110911889-480b3280-8339-11eb-9f98-fe449b0a1a4f.png)

2021-03-12 08:19 UTC, Kajol-Kumari commented on frontend/src/pages/Admin/Components/MangeTeams/ManageTeams.jsx
> +    {
let's put these data under `test_data/teams.json` [All testing data are kept there] Pleasenote that we don't have a file named `teams.json` so please create it under `test_data` folder

2021-03-12 08:32 UTC, Kajol-Kumari commented on frontend/src/pages/Admin/Components/AddTeamMember/AddTeamMember.jsx
> +              <label className={styles["add-team-member-label-text"]}>Teams :</label>
Let's keep it's color black/grey(same as input fields place-holder) In order to be cosistent

2021-03-12 19:03 UTC, Shubham-Kumar-2000 commented
All the required changes made.

@Kajol-Kumari

2021-03-13 06:08 UTC, Kajol-Kumari approved these changes
Nice and Clean! LGTM :+1: 
Thanks for incorporating the suggested changes @Shubham-Kumar-2000

2021-03-13 06:09 UTC, merged