Refactored broadcast page
HITK-TECH-Community/Community-Website pull request #541
Opened 2021-03-18 12:18 UTC by FireQueen-3010

## Issue that this pull request solves

 For : #490 (Broadcast section)

## Proposed changes

### Brief description of what is fixed or changed

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [X] Other (please describe): Refactored Broadcasts page

## Checklist

_Put an `x` in the boxes that apply_

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

2021-03-18 12:19 UTC, FireQueen-3010 commented
@Kajol-Kumari Please review and let me know regarding the pr!

2021-03-18 13:33 UTC, Kajol-Kumari requested changes
@FireQueen-3010 Please do the following changes-
1. Reduce the word limit from 600 to 420 or 450 [here](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/pages/Broadcast/Component/Carousel/Carousel.jsx#L73)
2. The View modal for large screens(not XL) get's hidden a bit, Can you please fix that as well? I will merge this under `level-3` then :)

Large screen view Broadcast Bug :arrow_down: 
![Screenshot from 2021-03-18 18-57-28](https://user-images.githubusercontent.com/44888949/111634532-a003d680-881c-11eb-9ff0-cac17756c1ba.png)

2021-03-18 13:33 UTC, Kajol-Kumari commented on frontend/src/pages/Broadcast/Component/Carousel/Modal/modals.module.scss
> +.link {
please leave one blank line space here

2021-03-18 13:33 UTC, Kajol-Kumari commented on frontend/src/pages/Broadcast/Component/Carousel/Modal/modals.module.scss
> +.link:hover {
same here. One line space

2021-03-18 13:33 UTC, Kajol-Kumari commented on frontend/src/pages/Broadcast/Component/Carousel/Modal/modals.module.scss
> +.close-btn {
same here. One line space

2021-03-18 13:33 UTC, Kajol-Kumari commented on frontend/src/pages/Broadcast/Component/Carousel/Modal/modals.module.scss
> +.close-btn:hover {
same here. One line space

2021-03-18 13:33 UTC, Kajol-Kumari commented on frontend/src/pages/Broadcast/Component/Carousel/carousel.module.scss
> +  font-size: 25px;
let's keep it `24px`

2021-03-18 13:36 UTC, FireQueen-3010 commented
Ok @Kajol-Kumari

2021-03-18 13:38 UTC, FireQueen-3010 commented on frontend/src/pages/Broadcast/Component/Carousel/Modal/modals.module.scss
> +.link:hover {
before .link:hover right?

2021-03-18 14:29 UTC, FireQueen-3010 commented
Done @Kajol-Kumari  with all of that :)

2021-03-18 15:38 UTC, Kajol-Kumari commented
Hey @FireQueen-3010 my screen resolution is `1366x768` and I am still facing that large screen bug. Can you please verify and fix it?

2021-03-18 16:09 UTC, FireQueen-3010 commented
Okay

2021-03-19 05:05 UTC, Kajol-Kumari approved these changes
Hey @FireQueen-3010 Thanks for incorporating all the suggested changes
LGTM :+1: 

Just a note -  From next time don't use `git add .` instead use `git add <file_name>` so that you don't add `package-lock.json` file in the commit :)

2021-03-19 05:06 UTC, merged

2021-03-19 05:08 UTC, FireQueen-3010 commented
Yeah sure I'll keep that in mind the next time @Kajol-Kumari . Thank you so much! 😄