Expire token
HITK-TECH-Community/Community-Website pull request #550
Opened 2021-03-21 07:49 UTC by garvitgupta13

## Issue that this pull request solves

 Closes: #503 

## Proposed changes

### Brief description of what is fixed or changed
As the jwt token expires it call the logout function and the admin is logged out from the dashboard. For this I have used the jwt-decode package to decode the token.

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

## Other information

Any other information that is important to this pull request

2021-03-22 05:53 UTC, Kajol-Kumari requested changes
Just to add on, when we logout the user can we please show the toast message of `Please login again!` instead of `successfully logged out!`

2021-03-22 05:53 UTC, Kajol-Kumari commented on frontend/src/pages/Admin/Admin.jsx
> +      // console.log("Decoded token: ", decode(token));
Hey @garvitgupta13 Can we please these commented lines

2021-03-22 07:53 UTC, garvitgupta13 commented
Mam I have tried to add a toast message by adding a key "expired" to localstorage before I call the logout function in key expire function but I don't know why it has created a new login error. Now when I try to login I face a backend issue.
These are the changes I made to Login.jsx
![image](https://user-images.githubusercontent.com/70805691/111956612-fb7ddf00-8b10-11eb-9993-21039a5ae64a.png)
`expired`:
![image](https://user-images.githubusercontent.com/70805691/111957062-8b238d80-8b11-11eb-98c7-87d8fadc1dd3.png)

Error I am facing:
![image](https://user-images.githubusercontent.com/70805691/111956729-1f412500-8b11-11eb-845f-7ba0a35c124a.png)
I have not made any changes to any backend file.
Can you please guide me

2021-03-22 08:39 UTC, Kajol-Kumari commented
Hey @garvitgupta13 that's not the issue with your code. Seems like someone has messed up with the database again. We will fix it soon and get back to you

2021-03-22 08:44 UTC, Kajol-Kumari commented
> Hey @garvitgupta13 that's not the issue with your code. Seems like someone has messed up with the database again. We will fix it soon and get back to you

This has been fixed now. Please try now.

2021-03-22 16:51 UTC, garvitgupta13 commented
What should be the `severity` of toast message: error , info , success.
All changes are done, soon I will be pushing them

2021-03-22 19:14 UTC, garvitgupta13 commented
Mam, please add the necessary `gssoc21` labels

2021-03-23 05:04 UTC, Kajol-Kumari commented
> What should be the `severity` of toast message: error , info , success.
> All changes are done, soon I will be pushing them

Please keep it `info`

2021-03-23 13:06 UTC, Kajol-Kumari approved these changes
Hey @garvitgupta13 Thanks for patiently incorporating all the suggested changes.
Looks good to go now :)

2021-03-23 13:07 UTC, merged