Feature/contact us form
HITK-TECH-Community/Community-Website pull request #605
Opened 2021-04-09 08:00 UTC by rohithmsr

## Issue that this pull request solves

 Closes: #499 

## Proposed changes

### Brief description of what is fixed or changed

Contact Us Model to store the response of the users is created and as soon as the user sends the response, an email is sent
to the admins following a template mentioned in utility folder.

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface
------------

## Other information

Any other information that is important to this pull request

2021-04-11 12:53 UTC, jackfrost13 requested changes
Please refactor the required things, Also you need to provide the api testing file(mocha-chai) and a brief backend documentation for the module

2021-04-11 12:53 UTC, jackfrost13 commented on backend/app/models/ContactUs.js
> +module.exports = mongoose.model('ContactUsUsers', contactUsUserSchema);
This should be just contactUs. Applicable for everywhere

2021-04-11 12:53 UTC, jackfrost13 commented on backend/app/routes/contactus/@validationSchema/index.js
> +  name: Joi.string()
for this everything is requried

2021-04-11 12:53 UTC, jackfrost13 commented on backend/app/routes/contactus/getAdmins.js
> +
We already have a function for this, please you that

2021-04-11 12:53 UTC, jackfrost13 commented on backend/app/routes/contactus/@validationSchema/index.js
> +const postResponseSchema = Joi.object({
name should be postContactUsValidationSchema

2021-04-11 12:53 UTC, jackfrost13 commented on backend/app/routes/contactus/sendEmails.js
> +    emails.map(async (item) => {
you can directly call the send mail with a list of emails

2021-04-11 12:53 UTC, jackfrost13 commented on backend/app/routes/contactus/postResponse.js
> +    your_response: response,
this response shouldn't be sent. You are not filtering the response

2021-04-11 12:53 UTC, jackfrost13 commented on .gitignore
> +backend/.env
this shouldn't be ignored for now

2021-05-09 16:19 UTC, jackfrost13 commented
@rohithmsr Are you working on this?

2021-05-09 16:29 UTC, rohithmsr commented
No

On Sun, 9 May, 2021, 9:49 pm Rohit Agarwal, ***@***.***>
wrote:

> @rohithmsr <https://github.com/rohithmsr> Are you working on this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/HITK-TECH-Community/Community-Website/pull/605#issuecomment-835837542>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APOBBVO5CNAMS77NCU5SXQTTM2YYRANCNFSM42UO5WYA>
> .
>

2021-05-10 10:54 UTC, closed without merging