Enhancement in Join Us section
HITK-TECH-Community/Community-Website pull request #620
Opened 2021-04-18 06:56 UTC by AbhipsaGuru1012

## Issue that this pull request solves

 Closes: #619 

## Proposed changes
Center aligned the text in Join Us section

### Brief description of what is fixed or changed
Center aligned the text in Join Us section in home page

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface
![JoinUs](https://user-images.githubusercontent.com/58511560/115137032-39ebb880-a041-11eb-99a8-fee3875abb0e.PNG)

## Other information

Any other information that is important to this pull request

2021-04-21 14:10 UTC, Kajol-Kumari requested changes
Hey @AbhipsaGuru1012 can we please reduce the spacing btw the heading and the content of the join us section. Currently we have a lot of spacing between them

2021-04-21 16:45 UTC, AbhipsaGuru1012 commented
> Hey @AbhipsaGuru1012 can we please reduce the spacing btw the heading and the content of the join us section. Currently we have a lot of spacing between them

Sure. I will make the changes

2021-04-21 17:15 UTC, AbhipsaGuru1012 commented
@Kajol-Kumari I have made the changes. Please let me know if this is okay

2021-04-23 15:19 UTC, Kajol-Kumari approved these changes

2021-04-23 15:20 UTC, merged