Delete and Get FAQ endpoints added
HITK-TECH-Community/Community-Website pull request #673
Opened 2021-12-11 07:09 UTC by naveen8801

## Issue that this pull request solves

 Closes: #668 

## Proposed changes

* Added two new endpoints for API - /Getfaq and /deleteFaq
* /Getfaq will return all FAQs available in db.
* /deleteFaq will delete a particular FAQ from the db, it is basically a PUT request and its payload should be:
```
{
    userId
    faqId
}
```

## Types of changes

_Put an `x` in the boxes that apply_

- [x] New feature (non-breaking change which adds functionality)

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

![image](https://user-images.githubusercontent.com/54985099/145667791-60d62444-a92c-4c6f-bb06-80cc7bf6f5b4.png)
![image](https://user-images.githubusercontent.com/54985099/145667813-31e25a98-e84b-4069-99cc-a2345224555e.png)

2021-12-12 12:54 UTC, Kajol-Kumari requested changes
@naveen8801 Pease do the below changes-
1. Rename `DeleteFaq.js` to `deleteFaq.js`
2. Rename `GetFaq.js` to `deleteFaq.js`

Also, try not to include `package-lock.json` file or `yarn.lock` files while making the PR

2021-12-12 12:54 UTC, Kajol-Kumari commented on backend/app/routes/faq/DeleteFaq.js
> +const FAQ = require('../../models/faq');
Please rename `FAQ` to `Faq`

2021-12-12 12:54 UTC, Kajol-Kumari commented on backend/app/routes/faq/DeleteFaq.js
> +      message: 'No Admin',
Please update the message with `You don't have the required permissions`

2021-12-12 12:54 UTC, Kajol-Kumari commented on backend/app/routes/faq/DeleteFaq.js
> +      message: 'No FAQ found',
please replace the message as `Faq doesn't exist`

2021-12-12 12:54 UTC, Kajol-Kumari commented on backend/app/routes/faq/GetFaq.js
> +      message: 'Database Error',
Please replace the message as `Mongo Error: Fetching Failed`

2021-12-12 12:54 UTC, Kajol-Kumari commented on backend/app/routes/index.js
> +const GetFaq = require('./faq/GetFaq');
please use camelCase in variable and usenames for eg thi sline can be replaced with - 
`const getFaq = require('./faq/get-faq');`

2021-12-12 12:54 UTC, Kajol-Kumari commented on backend/app/routes/index.js
> +const DeleteFaq = require('./faq/DeleteFaq');
Please replace above line with-
`const deleteFaq = require('./faq/delete-faq');`

and make the required change in `faq/index.js` file

2021-12-12 15:59 UTC, naveen8801 commented
Hey @Kajol-Kumari, made requested changes to filenames and variable names but can't able to ignore package-lock.json and yarn.lock, i would be thankful if you can help me out :)

2021-12-13 15:35 UTC, Kajol-Kumari requested changes
@naveen8801 Can you please mention somewhere in the PR description the program under which you have made this PR?

2021-12-15 05:21 UTC, naveen8801 commented
> @naveen8801 Can you please mention somewhere in the PR description the program under which you have made this PR?

Hi @Kajol-Kumari , added it in PR description, you can check, and made all the requested changes :)

2021-12-15 06:38 UTC, Kajol-Kumari approved these changes
@naveen8801 Thanks for making the requested changes.

LGTM 👍

2021-12-15 06:41 UTC, merged