[Backend] Contact Us Delete Cron Job added
HITK-TECH-Community/Community-Website pull request #712
Opened 2022-02-12 12:44 UTC by Aniket-508

## Issue that this pull request solves

 Closes: #697 

### Brief description of what is fixed or changed

- Added Contact Us CronJob email template that will be sent to Admin when deletion takes place.
- The CronJob for Contact Us would execute after every 60 days.

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

NA

## Other information

This PR is raised under JWoC.

2022-02-12 12:44 UTC, Aniket-508 commented
@Kajol-Kumari Please have a look at this.

2022-02-13 07:23 UTC, Kajol-Kumari requested changes
@Aniket-508 Please do the requested minor changes required.
Rest, looks good to go

2022-02-13 07:23 UTC, Kajol-Kumari commented on backend/utility/emailTemplates.js
> +  Contact Us Data has been removed !
Please change it to `The Contact Us Form data of last 2 month has been removed!`

2022-02-13 07:23 UTC, Kajol-Kumari commented on backend/index.js
> +cronJob('0 0 1 * *', async () => {
Can we please make it for `2 months` in order to keep the things consistent

2022-02-13 10:39 UTC, Aniket-508 commented
@Kajol-Kumari Can you check it now?

2022-02-13 15:20 UTC, Kajol-Kumari approved these changes
LGTM 👍

2022-02-13 15:21 UTC, merged