Added delete functionality in manage broadcast page with Admin access…
HITK-TECH-Community/Community-Website pull request #713
Opened 2022-02-19 10:23 UTC by Aniket-508

## Issue that this pull request solves

 Closes: #682 

### Brief description of what is fixed or changed
In the 'all-broadcasts' page itself, if logged in as admin provided access to delete broadcasts by calling suitable api with the id being passed as a param.

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

https://user-images.githubusercontent.com/71957423/154796928-be0e809f-4947-4ca0-9ed7-be274cfa85d0.mp4

2022-02-19 10:24 UTC, Aniket-508 commented
@Kajol-Kumari Please have a look at this.

2022-02-19 15:35 UTC, Kajol-Kumari requested changes
Hi @Aniket-508 Thanks for coming up with the PR. Few changes are required related to the UI-
- The `Manage Broadcast` page of Admin Dashboard should take us to a **new page** [it should also be inside the admin dashboard only ] and this new page should have a title as `Manage Broadcasts` and render all the broadcasts here similar to [this](https://deploy-preview-713--hitk-tech-community.netlify.app/all-broadcasts) Page
- Remove the delete and edit icon and feature from [this](https://deploy-preview-713--hitk-tech-community.netlify.app/all-broadcasts) page and keep it only on the new `Manage Broadcast` page that will be present under admin dashboard.

Please let me know if you need nay further clarification on this. We can sync, if required :)

2022-02-19 18:16 UTC, Aniket-508 commented
@Kajol-Kumari I think we should sync probably for better understanding!

2022-02-22 02:51 UTC, Kajol-Kumari commented
> @Kajol-Kumari I think we should sync probably for better understanding!

Sure... Please hop in at https://join.slack.com/t/hitkteckcommunity/shared_invite/zt-njgae7ki-Xn1y4Nmc_bwqwU~tN52vrg and we can take our further discussion in there.

2022-03-06 09:56 UTC, closed without merging