some change in footer
HITK-TECH-Community/Community-Website pull request #717
Opened 2022-02-28 04:49 UTC by tanktejas

=> added Twitter and youtube icons in the footer.
=> add email in the footer.

2022-03-10 11:16 UTC, Kajol-Kumari requested changes
@tanktejas please do the following changes -
1. The minor enhacements suggetsed
2. Replace `email` icon with `instagram` icom

2022-03-10 11:16 UTC, Kajol-Kumari commented on frontend/src/components/Footer/footer.module.scss
> +.footer_footer-addr__pYXWE {
please remove this as it's not required

2022-03-10 11:16 UTC, Kajol-Kumari commented on frontend/src/components/Footer/footer.module.scss
> +.footer div {
please leave one line blank before starting a new class

2022-03-10 11:16 UTC, Kajol-Kumari commented on frontend/src/components/Footer/footer.module.scss
> +}
please leave one line blank before starting a new class

2022-05-09 18:42 UTC, AyushSingh22 reviewed
Any Update?? @tanktejas

2024-05-28 17:56 UTC, harshcodesit commented
My name is Harshwardhan Singh Panwar and I'm a contributor at GSSOC'24 .

idea:- By incorporating div CSS and animations, I can design the UI in an interactive manner, making it visually appealing.

Please assign this task to me, GSSOC'24 .

2024-08-10 05:41 UTC, closed without merging