Enhancement: Add Broadcast Form
HITK-TECH-Community/Community-Website pull request #745
Opened 2022-03-05 11:12 UTC by Lalit3716

## Issue that this pull request solves

 Closes: #739 
## Proposed changes
- Added More Fields in Add Broadcast Form
- Added validation too for form

### Brief description of what is fixed or changed
- Changed UI + Enhanced validation

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [x] Other (please describe):  UI Changes

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

![Screenshot 2022-03-05 162440](https://user-images.githubusercontent.com/84276404/156880601-4a2858ad-42f0-43f8-bc65-df259b3ef132.png)

## Other information

I don't know how but for some reason my package-lock.json file had too many changes for no reason :(.
But it still works properly for me :)

2022-03-05 13:17 UTC, Kajol-Kumari requested changes
Hey @Lalit3716 can we please make the uI of this form similar to the other forms that we have for eg - [contact-us-form] (https://hitk-tech-community.netlify.app/contact-us)

2022-03-05 15:01 UTC, Lalit3716 commented
> Hey @Lalit3716 can we please make the uI of this form similar to the other forms that we have for eg - [contact-us-form] (https://hitk-tech-community.netlify.app/contact-us)

Yeah sure! I will try to make the UI similar.

2022-03-08 13:46 UTC, Lalit3716 commented
Will Do all the requested changes soon !

2022-03-09 12:59 UTC, Kajol-Kumari requested changes
@Lalit3716 Minor changes -
Please make the broadcast card in the centre of the parent card [vertically centered as well]
<img width="1665" alt="Screenshot 2022-03-09 at 6 28 26 PM" src="https://user-images.githubusercontent.com/44888949/157446355-718c1154-0e2f-49e9-bbcd-fec5fbad8e26.png">

2022-03-09 12:59 UTC, Kajol-Kumari commented on frontend/src/pages/Admin/Components/Broadcast/AddBroadcasts/AddBroadcasts.jsx
> +              placeholder="Broadcast Date(DD/MM/YY)"
this is not coming in the frontend. Can you please check once?

2022-03-21 14:27 UTC, Kajol-Kumari commented on frontend/src/pages/Admin/Components/Broadcast/AddBroadcasts/AddBroadcasts.jsx
> +              placeholder="Broadcast Date(DD/MM/YY)"
@Lalit3716 Can we please make this minor change so that I can merge this pr?

2022-03-26 06:16 UTC, merged