Backend API for uploading resources
HITK-TECH-Community/Community-Website pull request #747
Opened 2022-03-05 14:38 UTC by AdnanMuzavor

## Issue that this pull request solves

 Closes:#736

## Proposed changes:
->Created Model for resources as specified
->Created API for posting Resources
->If important fields are not filled specific error is thrown
->If schema is not followed i.e string used instead of int, error is thrown
### Brief description of what is fixed or changed

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update (Documentation content changed)
- [x] Other (please describe): Added an ERROR  constant " REQEMPTYFIELDS", It specifies that certain important fields cannot be left empty.

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface
[](url)
## Other information

resources model screen shot: 
![Screenshot (697)](https://user-images.githubusercontent.com/78341720/156887905-7d1134b3-4350-4eb9-be20-4007f18f86a2.png)

addresource function:
![Screenshot (698)](https://user-images.githubusercontent.com/78341720/156887911-7182549b-841d-4389-b5e5-20aaa2a8b3ac.png)

![Screenshot (699)](https://user-images.githubusercontent.com/78341720/156887928-a351eead-71b8-49e4-95c2-a5d30040869a.png)

index.js in resource folder:
![Screenshot (700)](https://user-images.githubusercontent.com/78341720/156887935-ddc34b82-1672-49e0-8659-dd14c1694988.png)
 
index.js in routes folder:
![Screenshot (701)](https://user-images.githubusercontent.com/78341720/156887947-bbe2bae8-91aa-4ad2-9220-db89fd89ddaa.png)

constants.json (to show additional constant added):
![Screenshot (702)](https://user-images.githubusercontent.com/78341720/156887962-d50bd5ab-27f1-4f75-b571-ed814b4a8571.png)

Any other information that is important to this pull request

Here is recording of API testing: https://www.recordjoy.com/view/39lxUuSciSeGUoM5AWuH
1)When all content is properly provided
2)When something required is missing example "name"
3)When wrong data types are used(string in place of integer)

2022-03-05 17:23 UTC, Kajol-Kumari requested changes
@AdnanMuzavor please make the requested changes and also add the test for this api

2022-03-05 17:23 UTC, Kajol-Kumari commented on backend/app/routes/resources/addResource.js
> +    const { name, email, url, trustLevel, expiryDate } = req.body;
We use the validation Schema to add check for the required field. Please see https://github.com/HITK-TECH-Community/Community-Website/pull/695/files#diff-66eaadabdfb2a1e580497efec3551b7ff1a144afc8f0d2732ba5643b0032f3c3R1 this pr for reference

2022-03-05 17:23 UTC, Kajol-Kumari commented on backend/app/routes/resources/addResource.js
> +    res.status(200).send(newResource);
After successful addition, we want to send the email to all the admins. Please refer https://github.com/HITK-TECH-Community/Community-Website/pull/695/files#diff-570f5e87cc8f64b44733c6e3209357e3450f7fb88a038466acd1c43781150d28R30 for the reference

2022-03-05 17:23 UTC, Kajol-Kumari commented on backend/constants/constants.json
> +    "REQEMPTYFIELDS":"Required Fields Not Filled"
We won't need this variable after implementing the above commented approach. So, you can get rid of it.

2022-03-06 09:11 UTC, Kajol-Kumari requested changes
@AdnanMuzavor please do the minor requested changes.

2022-03-06 09:11 UTC, Kajol-Kumari commented on backend/constants/constants.json
> +
please revert the change of this file

2022-03-06 09:11 UTC, Kajol-Kumari commented on backend/app/routes/resources/index.js
> +//Creating a router
please remove the comments from this file as imports are understandable

2022-03-06 09:11 UTC, Kajol-Kumari commented on backend/app/routes/resources/addResource.js
> +//Getting resource modal
please remove comment from imports

2022-03-06 11:53 UTC, AdnanMuzavor commented on backend/app/routes/resources/addResource.js
> +//Getting resource modal
Okay Ma'am.

2022-03-06 13:16 UTC, Kajol-Kumari approved these changes
Thanks for making the required changes @AdnanMuzavor 
LGTM 👍

2022-03-06 13:18 UTC, merged