get admin details implemented on endpoint /admin
HITK-TECH-Community/Community-Website pull request #761
Opened 2022-03-11 09:58 UTC by Gurdeep475

## Issue that this pull request solves

 Closes: #476 

## Proposed changes
added simple if the check for adminType and fetched the details of admin using email attacked with the request body.

### Brief description of what is fixed or changed
endpoint /admin now returns single logged-in admin details for non-super admins
## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots
![image](https://user-images.githubusercontent.com/32095032/157844698-9869db81-cc71-422d-807d-be732dd184cf.png)

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

2022-03-13 09:00 UTC, Kajol-Kumari requested changes
@Gurdeep475 This is an existing api for getting the list of admins. Please make a separate api for getting the details of the loggedin admin. [ You can name it under `getAdmin.js` ]

2022-03-14 05:00 UTC, Gurdeep475 commented
> @Gurdeep475 This is an existing API for getting the list of admins. Please make a separate api for getting the details of the logged-in admin. [ You can name it under `getAdmin.js` ]

But the original issue asked to implement in the existing /admin API endpoint.

2022-03-22 18:07 UTC, Gurdeep475 commented on backend/app/routes/admin/getAdmins.js
> +    const adminDetails = await Admin.find({email: req.body.email});
@Kajol-Kumari I have made the necessary changes according to the instructions provided.

2022-03-23 12:29 UTC, Kajol-Kumari approved these changes
LGTM 👍

2022-03-23 12:30 UTC, merged