[Frontend] Integrate Ask Question Form With Backend
HITK-TECH-Community/Community-Website pull request #786
Opened 2022-04-08 15:11 UTC by Aman16-ai

## Issue that this pull request solves

 Closes: #783 

## Proposed changes

- integrating with backend

### Brief description of what is fixed or changed

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots
![Screenshot (786)](https://user-images.githubusercontent.com/74807466/162470856-76216d1e-74d2-4075-a0ec-910cd41f308d.png)
![Screenshot (787)](https://user-images.githubusercontent.com/74807466/162470846-119657a4-219a-4591-b955-b6173b1f7550.png)

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

2022-04-13 04:12 UTC, Kajol-Kumari requested changes
@Aman16-ai Form validation isn't getting handled properly here. If any of the required field is empty, the api call shouldn't happen. But here I can see the success msg, although I got `400` in api response.

Ref - 
<img width="1134" alt="Screenshot 2022-04-13 at 9 38 51 AM" src="https://user-images.githubusercontent.com/44888949/163098657-9b5da8bd-1e7f-44d0-9c66-f7415e066a70.png">

2022-04-13 04:12 UTC, Kajol-Kumari commented on frontend/src/pages/Q&A/Q&A.jsx
> +      console.log(data)
please remove all console.log statements

2022-04-13 04:12 UTC, Kajol-Kumari commented on frontend/src/pages/Q&A/Q&A.jsx
> +    console.log(formdata)
please remove all console.log statements

2022-04-13 04:12 UTC, Kajol-Kumari commented on frontend/src/pages/Q&A/Q&A.jsx
> +      console.log(err)
please remove it

2022-04-16 08:40 UTC, Aman16-ai commented
**fixed all validation bugs**
https://user-images.githubusercontent.com/74807466/163668459-767b6ad2-4174-405b-b7ed-e15be20aadce.mp4

2022-04-22 09:27 UTC, Kajol-Kumari approved these changes

2022-04-22 09:27 UTC, merged