Update Admin
HITK-TECH-Community/Community-Website pull request #796
Opened 2022-04-24 13:26 UTC by mayank-del

## Issue that this pull request solves

 Closes: # (issue number)

## Proposed changes
added update-admin api

### Brief description of what is fixed or changed
update admin route added with requires changes

## Types of changes

_Put an `x` in the boxes that apply_

- [ x] New feature (non-breaking change which adds functionality)
- [x ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply_

- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code

- [ x] My changes generate no new warnings
- [x ] My changes does not break the current system and it passes all the current test cases.

2022-04-26 05:41 UTC, Kajol-Kumari requested changes
@mayank-del few points to consider here while writing the apis-
1. Always try to use `try - catch` block and return relevant message wherever possible.
2. For success response, please return the id of the data that got updated
3. Write tests for the the api you write
4. Remove all `console.log` statements 
ref - please refer [this](https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/contactUs/post.js) file for writing a clean api

2022-04-27 15:37 UTC, mayank-del commented
Should we use mongoDb id or own created id?

2022-04-28 10:11 UTC, mayank-del commented
please check it once

2022-05-06 10:57 UTC, aakankshabhende approved these changes

2022-05-06 10:59 UTC, merged