created code_of_conduct.md file
HITK-TECH-Community/Community-Website pull request #83
Opened 2020-12-27 14:01 UTC by Sloth-Panda

## Issue that this pull request solves

 Closes:  #(75)

## Proposed changes

### Brief description of what is fixed or changed
Made code_of_conduct.md  file

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

2020-12-27 14:02 UTC, Sloth-Panda commented
Hey, Let me know if any changes are required

2020-12-27 14:18 UTC, Kajol-Kumari requested changes
@Sloth-Panda please make this minor change and it will be good to go :)

2020-12-27 14:18 UTC, Kajol-Kumari commented on code_of_conduct.md
> +reported by contacting a project maintainer at [INSERT EMAIL ADDRESS]. All
please replace `[INSERT EMAIL ADDRESS]` by `hitktechcommunity@gmail.com`

2020-12-27 14:46 UTC, Sloth-Panda commented
Hey, can you check this out now?

2020-12-27 14:49 UTC, Kajol-Kumari approved these changes
LGTM :+1:

2020-12-27 14:50 UTC, merged

2020-12-27 14:50 UTC, Kajol-Kumari commented
@all-contributors please add @Sloth-Panda  for doc

2021-03-01 04:17 UTC, Sloth-Panda commented
@Kajol-Kumari is not this pr counted for swoc?