add the Delete feat in join us - Admin
HITK-TECH-Community/Community-Website pull request #831
Opened 2024-01-13 12:41 UTC by sohail300

## Issue that this pull request solves

 Closes: # 790

## Proposed changes
- [x] The join Us cards under the admin panel should not have the URL button as it doesn't seem to require
- [x] The LinkedIn text should open the linkedIn url in a new Page
- [x] The delete button should call the delete api with proper toast message

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ x] My changes does not break the current system and it passes all the current test cases.

## Screenshots
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/144511967/f7fb5293-53f7-4f82-ab67-441ac62ff991)

2024-01-16 04:32 UTC, thevirengarg commented
Add a screen recording of the changes you made

2024-01-16 11:57 UTC, Kajol-Kumari requested changes
please share a screen recording showing the delete api call in the network tab, so that I can confirm the functionality. Also, please make sure you maintain the responsiveness of the page

2024-01-16 11:57 UTC, Kajol-Kumari commented on frontend/src/pages/Admin/Components/JoinUs/Card/card.module.scss
> +// .dot-loader {
[neat] remove the commented code if not required

2024-01-20 05:56 UTC, thevirengarg requested changes
@sohail300 Are you working on this pull request??

2024-01-20 15:26 UTC, Kajol-Kumari requested changes
So, I was able to pull your changes and test it on my local. There are few comments - 
1. The deletion is happening but the ui isn't refreshing i.e the deleted card is still appearing on the page
2. The UI seems off, please fix it.

2024-01-21 13:43 UTC, Aditi-Dahiya requested changes
UI styling needs to be addressed.

2026-02-07 14:22 UTC, closed without merging