Social icons animation in footer & "email required" message bug fixed.
HITK-TECH-Community/Community-Website pull request #840
Opened 2024-01-26 10:21 UTC by adi-exe

## Issue that this pull request solves

 Closes: #828 Footer Email Input Validation Message Appears Unnecessarily When Input is Not Provided; Social media icons fails animation on hover IWOC

## Proposed changes

1. Footer Email Input Validation:
When the email input box in the footer is active, the validation message indicating "email required" was appearing even when no input is provided. This has been fixed now, it doesn't show this message unnecessarily.

2. Social Media Icons Animation:
Previously on hovering over the social media icons in the footer, instagram , twitter , youtube failed to display the expected animation. I have added the particular animation to them.

3. Placeholder of email input:
The placeholder remained the same dark colored even on focus if the input .
I have added a light grey color to make is more pleasing to user.

### Brief description of what is fixed or changed

## Types of changes

_Put an `x` in the boxes that apply_

- [ x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

![Screenshot (124)](https://github.com/HITK-TECH-Community/Community-Website/assets/134140404/245bd944-9c83-41bc-8d54-7b87efe1507c)
![Screenshot (125)](https://github.com/HITK-TECH-Community/Community-Website/assets/134140404/bbf579e6-5278-4c1b-bf4f-05f43af881d2)
![Screenshot (126)](https://github.com/HITK-TECH-Community/Community-Website/assets/134140404/90ee8fb2-89db-4a4e-ba54-a864c888b880)

## Other information

Any other information that is important to this pull request

2024-01-26 19:16 UTC, thevirengarg requested changes
The message "Email is required" should be visible if the email input field is focused but is empty and as soon as user starts typing the email it should clear the error message. If it's not selected it should display "Email ID".

2024-01-27 18:00 UTC, adi-exe commented
so basically we have to remove " * Please enter valid Email " message ,
cause as soon as the user starts writing it shows this message.

2024-01-30 16:36 UTC, Kajol-Kumari requested changes

2024-01-30 16:36 UTC, Kajol-Kumari commented on frontend/src/components/Footer/Footer.jsx
> -      emailErr.emailRequired = "* Email is required";
retain this. This is an expected error message

2024-01-30 16:36 UTC, Kajol-Kumari commented on frontend/src/components/Footer/footer.module.scss
> +.fa-instagram:hover,
any specific reason of modfying the css? Why do we need to change these hover effects?

2024-02-06 13:44 UTC, adi-exe commented
@Kajol-Kumari @thevirengarg  pls reply to these changes, IWOC is ending soon.

2024-02-11 03:04 UTC, Kajol-Kumari commented on frontend/src/components/Footer/footer.module.scss
> +.fa-instagram:hover,
Its a favicon icon, so the icons u see on the footer for instagram is fa-instagram

2024-02-11 09:51 UTC, Kajol-Kumari approved these changes

2024-02-11 09:54 UTC, merged