getAdmin api integrated with profile page issue#767
HITK-TECH-Community/Community-Website pull request #902
Opened 2024-05-16 12:43 UTC by SwayamRana808

## Issue that this pull request solves

 Closes: #767 

## Proposed changes
getAdmin api integrated with profile page
### Brief description of what is fixed or changed
getAdmin api integrated with profile page [api](https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/admin/getAdmins.js#L34) 
## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface
![Screenshot 2024-05-16 181259](https://github.com/HITK-TECH-Community/Community-Website/assets/122097724/081fb77c-7f93-4cb4-a67a-4a971019799f)

## Other information

Any other information that is important to this pull request

2024-05-16 17:38 UTC, Kajol-Kumari requested changes
<img width="650" alt="Screenshot 2024-05-16 at 11 07 06 PM" src="https://github.com/HITK-TECH-Community/Community-Website/assets/44888949/6e889775-15fd-40fa-ad34-64e2f9f7be10">

If the value isn't present, let's not show `undefine/null` on the ui. Also, will the phone number appear on the ui if i added it later?

2024-05-16 17:43 UTC, SwayamRana808 commented
yes phone no. will be shown .
i will hide undefined

2024-05-16 17:50 UTC, SwayamRana808 commented
i have corrected **null/undefined** values
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/122097724/1efa9e8e-f3c2-4799-b63e-982177bc9207)

2024-05-17 03:21 UTC, Kajol-Kumari approved these changes

2024-05-17 03:21 UTC, merged