update functionality for Admin profile
HITK-TECH-Community/Community-Website pull request #931
Opened 2024-05-19 06:13 UTC by SwayamRana808

## Issue that this pull request solves

 Closes: #896 

## Proposed changes
[Frontend] Introduce Update Admin Functionality
### Brief description of what is fixed or changed
  Introduce Update Admin Functionality and also backend api updated 
## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

https://github.com/HITK-TECH-Community/Community-Website/assets/122097724/7b260dd2-71cb-4d47-ac23-f09d0f19de72

## Other information

Any other information that is important to this pull request

2024-05-19 06:28 UTC, Kajol-Kumari requested changes
<img width="1113" alt="Screenshot 2024-05-19 at 11 57 23 AM" src="https://github.com/HITK-TECH-Community/Community-Website/assets/44888949/1acb5d1b-c2b6-4280-9612-1b036ffcb8fe">

The update detail isn't getting reflected, atleast i should have seen the first name/lastname getting updated as image changes are in this pr

2024-05-19 06:28 UTC, Kajol-Kumari commented on backend/app/routes/admin/getAdmins.js
> -  return next();
we should retain it

2024-05-19 06:28 UTC, Kajol-Kumari commented on backend/app/routes/admin/updateAdmin.js
> -  res.send('Done');
we should retain this.

2024-05-20 15:32 UTC, Kajol-Kumari commented
@SwayamRana808 let me know when u are done fixing the requested changes as i can see the current state of this pr is not good, a lot of un-necessary changes are there and functionality is still not intact

2024-05-20 16:23 UTC, SwayamRana808 commented
**i have changed response json but still it showing in network tab**

![Screenshot 2024-05-20 212920](https://github.com/HITK-TECH-Community/Community-Website/assets/122097724/7c8ccca9-ea9e-48bf-9e28-38bb142da62b)

**it should have shown something like this --**
![Screenshot 2024-05-20 213244](https://github.com/HITK-TECH-Community/Community-Website/assets/122097724/fa3988af-4601-46d4-875d-ef51fb94dc98)

**@Kajol-Kumari  can you please have look on this**

2024-05-22 16:12 UTC, Kajol-Kumari requested changes
<img width="376" alt="Screenshot 2024-05-22 at 9 40 52 PM" src="https://github.com/HITK-TECH-Community/Community-Website/assets/44888949/fbb223a7-cb00-4b78-9cea-fce10430e062">
The phone number field keeps on giving error, can u check this?

2024-05-22 16:24 UTC, SwayamRana808 commented
> <img alt="Screenshot 2024-05-22 at 9 40 52 PM" width="376" src="https://private-user-images.githubusercontent.com/44888949/332875016-fbb223a7-cb00-4b78-9cea-fce10430e062.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzOTUyOTAsIm5iZiI6MTcxNjM5NDk5MCwicGF0aCI6Ii80NDg4ODk0OS8zMzI4NzUwMTYtZmJiMjIzYTctY2IwMC00Yjc4LTljZWEtZmNlMTA0MzBlMDYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDE2MjMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlNGM0ODNmYjUxM2QyODdiYzBiOWU4NDc0MmU5MDY0NGQ1OGI5YjJiMDdjMmUyMWYwNmFkMmNmYTc0MWFmYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ylyowNBccTzFefxKhS4IxFpPBNtH5PlwlnTVLjULGhY"> The phone number field keeps on giving error, can u check this?

number should start with 9-6 it was validity check if number is from India its was already defined in backend

2024-05-22 16:30 UTC, merged