[Resource Sharing Form] fixed alignment of the input fields in the form
HITK-TECH-Community/Community-Website pull request #940
Opened 2024-05-20 18:23 UTC by shivamgaur99

## Issue that this pull request solves
 Closes: #935

fixed alignment of input text field of resource sharing form below are screenshots

## Types of changes
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist
_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/128178418/d1abd38c-4760-46a2-b087-ec183d0fd5ba)
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/128178418/046f285d-d865-47ea-abfe-282e13f2af72)

2024-05-22 16:18 UTC, Kajol-Kumari requested changes
<img width="406" alt="Screenshot 2024-05-22 at 9 47 47 PM" src="https://github.com/HITK-TECH-Community/Community-Website/assets/44888949/6cbebaf8-22b2-41d3-9d07-baaf6c7cf389">

it still breaking for `ipad mini` and `ipad air` screens, please fix the same

2024-05-22 18:02 UTC, shivamgaur99 commented
@Kajol-Kumari issue fixed, checked in all devices now its not breaking

![image](https://github.com/HITK-TECH-Community/Community-Website/assets/128178418/e563be6a-b870-4ab8-9e80-90f5e37aa05a)
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/128178418/d1a866e1-f89d-4926-912c-eb9934680a98)

2024-05-23 09:38 UTC, Kajol-Kumari requested changes
please revert `.env` change it will be good to be merged.

2024-05-23 09:38 UTC, Kajol-Kumari commented on backend/.env
> -MONGO_DB_URL=<mongoDB_URL>
cane we please revert this file change?

2024-05-23 10:00 UTC, shivamgaur99 commented on backend/.env
> -MONGO_DB_URL=<mongoDB_URL>
yeah sure

2024-05-23 16:21 UTC, merged