[Backend] Auth remove for post contact us Fixed
HITK-TECH-Community/Community-Website pull request #963
Opened 2024-05-25 03:53 UTC by Hemu21

## Issue that this pull request solves

[Issue Link](https://github.com/HITK-TECH-Community/Community-Website/issues/957) resolve #957 
 Closes: #957 

### Brief description of what is fixed or changed
Post contact us doesn't need auth, why because user post the data using contact us. Because of authentication user unable to post the data from contact us page. Now post contact us works fine.

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

2024-05-25 03:57 UTC, Hemu21 commented
@Kajol-Kumari  when you have a free time please check and merge it.

2024-05-25 14:43 UTC, Kajol-Kumari requested changes
@Hemu21 as this is for a level2 issue, can you also add middle ware here - https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/joinUs/index.js#L10

the delete and get call should only be accessible to admins

2024-05-25 14:43 UTC, Kajol-Kumari commented on backend/app/routes/contactUs/index.js
>  router.get('/getcontactus', getContact);
can u add the authMiddleware here as only admins should be able to fetch this data

2024-05-26 02:40 UTC, Hemu21 commented
@Kajol-Kumari updated can you please check.

2024-05-26 07:00 UTC, Kajol-Kumari approved these changes
LGTM

2024-05-26 07:01 UTC, merged